// <auto-generated />
using System;
using System.Collections.Generic;
using FaktureAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaktureAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220803134203_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaktureAPI.Models.BillBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillHeaderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CijenaDeviza")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CijenaKm")
                        .HasColumnType("numeric");

                    b.Property<string>("IznosRabata")
                        .HasColumnType("text");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PDV")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Rabat")
                        .HasColumnType("numeric");

                    b.Property<string>("Vrijednost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BillBodies");
                });

            modelBuilder.Entity("FaktureAPI.Models.BillHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumDospijeca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumIsporuke")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FiskalniBroj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KupacId")
                        .HasColumnType("integer");

                    b.Property<string>("MjestoIzdavanja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BillHeaders");
                });

            modelBuilder.Entity("FaktureAPI.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Banka")
                        .HasMaxLength(3)
                        .HasColumnType("text[]");

                    b.Property<string>("BrojPoste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mjesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pbr")
                        .HasColumnType("text");

                    b.Property<string>("Swift")
                        .HasColumnType("text");

                    b.Property<bool>("Tip")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });
#pragma warning restore 612, 618
        }
    }
}
